"""mfa challenges

Revision ID: aab86425d318
Revises: dca81bbf0da6
Create Date: 2026-09-16 08:55:17.384261
"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = 'aab86425d318'
down_revision: str | None = 'dca81bbf0da6'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mfa_challenges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('institution_id', sa.UUID(), nullable=True),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_mfa_challenges_user_id', 'mfa_challenges', ['user_id'], unique=False)
    # ### end Alembic commands ###

    # Autogenerate never emits RLS - mirror the same tenant-isolation policy
    # users/refresh_sessions already carry (see the initial migration), or
    # this table would be the one readable-across-tenants hole in identity.
    op.execute("ALTER TABLE mfa_challenges ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE mfa_challenges FORCE ROW LEVEL SECURITY")
    op.execute(
        """
        CREATE POLICY tenant_isolation ON mfa_challenges
        USING (
            current_setting('app.is_platform_admin', true) = 'true'
            OR institution_id = NULLIF(current_setting('app.current_institution_id', true), '')::uuid
        )
        WITH CHECK (
            current_setting('app.is_platform_admin', true) = 'true'
            OR institution_id = NULLIF(current_setting('app.current_institution_id', true), '')::uuid
        )
        """
    )


def downgrade() -> None:
    op.execute("DROP POLICY IF EXISTS tenant_isolation ON mfa_challenges")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_mfa_challenges_user_id', table_name='mfa_challenges')
    op.drop_table('mfa_challenges')
    # ### end Alembic commands ###
