"""camerpay redirect and provider transaction id

Revision ID: 4cc82d574c7a
Revises: 6e251544c56e
Create Date: 2026-09-16 07:22:59.554891
"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = '4cc82d574c7a'
down_revision: str | None = '6e251544c56e'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_intents', sa.Column('provider_transaction_id', sa.String(length=100), nullable=True))
    op.add_column('payment_intents', sa.Column('redirect_url', sa.String(length=500), nullable=True))
    # NOTE: autogenerate also wanted to drop 'uq_payment_intents_active_per_invoice'
    # here - a real, load-bearing partial unique index (see the initial
    # payments migration) not represented in the SQLAlchemy model, so it
    # always shows as a phantom diff. Deliberately NOT dropping it.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment_intents', 'redirect_url')
    op.drop_column('payment_intents', 'provider_transaction_id')
    # ### end Alembic commands ###
