"""finance phase 5 payments ledger campaigns summaries

Revision ID: 6e251544c56e
Revises: d2e3baf3eb78
Create Date: 2026-09-11 15:10:35.059723
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '6e251544c56e'
down_revision: str | None = 'd2e3baf3eb78'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('cost_xaf', sa.BigInteger(), nullable=False),
    sa.Column('starts_on', sa.Date(), nullable=False),
    sa.Column('ends_on', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_campaigns_institution_id', 'campaigns', ['institution_id'], unique=False)
    op.create_table('expenses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('amount_xaf', sa.BigInteger(), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('recorded_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount_xaf >= 0', name='ck_expenses_amount_nonnegative'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_expenses_institution_id', 'expenses', ['institution_id'], unique=False)
    op.create_table('financial_summaries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.Column('period', sa.Date(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('total_revenue_xaf', sa.BigInteger(), nullable=False),
    sa.Column('total_expenses_xaf', sa.BigInteger(), nullable=False),
    sa.Column('net_xaf', sa.BigInteger(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('institution_id', 'period', 'version', name='uq_financial_summaries_period_version')
    )
    op.create_index('ix_financial_summaries_institution_id', 'financial_summaries', ['institution_id'], unique=False)
    op.create_table('ledger_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.Column('posting_id', sa.UUID(), nullable=False),
    sa.Column('entry_type', sa.Enum('CASH', 'TUITION_REVENUE', 'EXPENSE', name='ledger_entry_type'), nullable=False),
    sa.Column('direction', sa.Enum('DEBIT', 'CREDIT', name='ledger_direction'), nullable=False),
    sa.Column('amount_xaf', sa.BigInteger(), nullable=False),
    sa.Column('reference_type', sa.String(length=50), nullable=False),
    sa.Column('reference_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount_xaf >= 0', name='ck_ledger_entries_amount_nonnegative'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ledger_entries_institution_id', 'ledger_entries', ['institution_id'], unique=False)
    op.create_index('ix_ledger_entries_posting_id', 'ledger_entries', ['posting_id'], unique=False)
    op.create_table('receipts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('payment_intent_id', sa.UUID(), nullable=False),
    sa.Column('amount_xaf', sa.BigInteger(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount_xaf >= 0', name='ck_receipts_amount_nonnegative'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_id', name='uq_receipts_invoice')
    )
    op.create_index('ix_receipts_institution_id', 'receipts', ['institution_id'], unique=False)
    op.create_table('leads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'QUALIFIED', 'CONVERTED', name='lead_status'), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_leads_campaign_id', 'leads', ['campaign_id'], unique=False)
    op.create_index('ix_leads_institution_id', 'leads', ['institution_id'], unique=False)
    op.create_table('payment_intents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('amount_xaf', sa.BigInteger(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_reference', sa.String(length=100), nullable=False),
    sa.Column('payer_msisdn', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SUCCEEDED', 'FAILED', name='payment_intent_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_reference')
    )
    op.create_index('ix_payment_intents_institution_id', 'payment_intents', ['institution_id'], unique=False)
    op.create_index('ix_payment_intents_invoice_id', 'payment_intents', ['invoice_id'], unique=False)
    op.create_index('ix_payment_intents_status', 'payment_intents', ['status'], unique=False)
    # ### end Alembic commands ###

    # Only one PENDING/SUCCEEDED intent may exist per invoice at a time -
    # a new attempt is only allowed once a prior one has terminally
    # FAILED (see phase5-plan.md).
    op.execute(
        """
        CREATE UNIQUE INDEX uq_payment_intents_active_per_invoice
        ON payment_intents (invoice_id)
        WHERE status IN ('PENDING', 'SUCCEEDED')
        """
    )

    # Row-level tenant isolation, same FORCE + SET LOCAL pattern as every
    # other tenant-owned table in this service.
    for table in (
        "campaigns",
        "expenses",
        "financial_summaries",
        "ledger_entries",
        "receipts",
        "leads",
        "payment_intents",
    ):
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"""
            CREATE POLICY tenant_isolation ON {table}
            USING (
                current_setting('app.is_platform_admin', true) = 'true'
                OR institution_id = NULLIF(current_setting('app.current_institution_id', true), '')::uuid
            )
            WITH CHECK (
                current_setting('app.is_platform_admin', true) = 'true'
                OR institution_id = NULLIF(current_setting('app.current_institution_id', true), '')::uuid
            )
            """
        )


def downgrade() -> None:
    for table in (
        "campaigns",
        "expenses",
        "financial_summaries",
        "ledger_entries",
        "receipts",
        "leads",
        "payment_intents",
    ):
        op.execute(f"DROP POLICY IF EXISTS tenant_isolation ON {table}")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_payment_intents_status', table_name='payment_intents')
    op.drop_index('ix_payment_intents_invoice_id', table_name='payment_intents')
    op.drop_index('ix_payment_intents_institution_id', table_name='payment_intents')
    op.drop_table('payment_intents')
    op.drop_index('ix_leads_institution_id', table_name='leads')
    op.drop_index('ix_leads_campaign_id', table_name='leads')
    op.drop_table('leads')
    op.drop_index('ix_receipts_institution_id', table_name='receipts')
    op.drop_table('receipts')
    op.drop_index('ix_ledger_entries_posting_id', table_name='ledger_entries')
    op.drop_index('ix_ledger_entries_institution_id', table_name='ledger_entries')
    op.drop_table('ledger_entries')
    op.drop_index('ix_financial_summaries_institution_id', table_name='financial_summaries')
    op.drop_table('financial_summaries')
    op.drop_index('ix_expenses_institution_id', table_name='expenses')
    op.drop_table('expenses')
    op.drop_index('ix_campaigns_institution_id', table_name='campaigns')
    op.drop_table('campaigns')
    # ### end Alembic commands ###
