"""finance initial schema

Revision ID: d2e3baf3eb78
Revises: 
Create Date: 2026-09-11 12:02:34.099706
"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = 'd2e3baf3eb78'
down_revision: str | None = None
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fee_schedules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.Column('program_id', sa.UUID(), nullable=False),
    sa.Column('term_id', sa.UUID(), nullable=False),
    sa.Column('amount_xaf', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount_xaf >= 0', name='ck_fee_schedules_amount_nonnegative'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('institution_id', 'program_id', 'term_id', name='uq_fee_schedules_program_term')
    )
    op.create_index('ix_fee_schedules_institution_id', 'fee_schedules', ['institution_id'], unique=False)
    op.create_table('inbox_events',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_table('invoices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.Column('enrollment_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('amount_xaf', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PAID', name='invoice_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount_xaf >= 0', name='ck_invoices_amount_nonnegative'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('institution_id', 'enrollment_id', name='uq_invoices_enrollment')
    )
    op.create_index('ix_invoices_institution_id', 'invoices', ['institution_id'], unique=False)
    op.create_index('ix_invoices_student_id', 'invoices', ['student_id'], unique=False)
    # ### end Alembic commands ###

    # Row-level tenant isolation. finance_app owns these tables (see
    # ops/postgres/init), so FORCE is required or it would bypass RLS as the
    # owner; finance_app is a plain LOGIN role (no BYPASSRLS/superuser), so
    # FORCE makes the policy apply to it too. Session-local
    # app.current_institution_id / app.is_platform_admin are set per-request
    # by app/core/tenant_context.py. inbox_events is intentionally excluded -
    # it is internal plumbing read only by this service's own consumer.
    for table in ("fee_schedules", "invoices"):
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"""
            CREATE POLICY tenant_isolation ON {table}
            USING (
                current_setting('app.is_platform_admin', true) = 'true'
                OR institution_id = NULLIF(current_setting('app.current_institution_id', true), '')::uuid
            )
            WITH CHECK (
                current_setting('app.is_platform_admin', true) = 'true'
                OR institution_id = NULLIF(current_setting('app.current_institution_id', true), '')::uuid
            )
            """
        )


def downgrade() -> None:
    for table in ("fee_schedules", "invoices"):
        op.execute(f"DROP POLICY IF EXISTS tenant_isolation ON {table}")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_invoices_student_id', table_name='invoices')
    op.drop_index('ix_invoices_institution_id', table_name='invoices')
    op.drop_table('invoices')
    op.drop_table('inbox_events')
    op.drop_index('ix_fee_schedules_institution_id', table_name='fee_schedules')
    op.drop_table('fee_schedules')
    # ### end Alembic commands ###
