"""hr phase 6 recruitment attendance leave performance assets payroll

Revision ID: 5e3c398fa17b
Revises:
Create Date: 2026-09-11 19:48:42.304199
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "5e3c398fa17b"
down_revision: str | None = None
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "assets",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("institution_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("category", sa.String(length=100), nullable=False),
        sa.Column("total_quantity", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("total_quantity >= 0", name="ck_assets_total_quantity_nonnegative"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_assets_institution_id", "assets", ["institution_id"], unique=False)
    op.create_table(
        "notifications",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("institution_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("message", sa.String(length=500), nullable=False),
        sa.Column("notified_via_email", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_notifications_institution_id", "notifications", ["institution_id"], unique=False)
    op.create_index("ix_notifications_user_id", "notifications", ["user_id"], unique=False)
    op.create_table(
        "payroll_schedule_versions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("institution_id", sa.UUID(), nullable=False),
        sa.Column("effective_from", sa.Date(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column("cnps_employee_rate", sa.Numeric(precision=6, scale=4), nullable=False),
        sa.Column("cnps_employer_rate", sa.Numeric(precision=6, scale=4), nullable=False),
        sa.Column("cnps_ceiling_xaf", sa.BigInteger(), nullable=False),
        sa.Column("standard_deduction_rate", sa.Numeric(precision=6, scale=4), nullable=False),
        sa.Column("irpp_brackets", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_payroll_schedule_versions_institution_id", "payroll_schedule_versions", ["institution_id"], unique=False
    )
    op.create_table(
        "positions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("institution_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("department", sa.String(length=100), nullable=False),
        sa.Column("status", sa.Enum("OPEN", "CLOSED", name="position_status"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_positions_institution_id", "positions", ["institution_id"], unique=False)
    op.create_table(
        "asset_movements",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("institution_id", sa.UUID(), nullable=False),
        sa.Column("asset_id", sa.UUID(), nullable=False),
        sa.Column("employee_id", sa.UUID(), nullable=True),
        sa.Column("quantity_delta", sa.Integer(), nullable=False),
        sa.Column("reason", sa.String(length=300), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["asset_id"], ["assets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_asset_movements_asset_id", "asset_movements", ["asset_id"], unique=False)
    op.create_index("ix_asset_movements_institution_id", "asset_movements", ["institution_id"], unique=False)
    op.create_table(
        "candidates",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("institution_id", sa.UUID(), nullable=False),
        sa.Column("position_id", sa.UUID(), nullable=False),
        sa.Column("full_name", sa.String(length=200), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column(
            "stage",
            sa.Enum("APPLIED", "SCREENING", "INTERVIEW", "OFFER", "HIRED", "REJECTED", name="candidate_stage"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["position_id"], ["positions.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_candidates_institution_id", "candidates", ["institution_id"], unique=False)
    op.create_index("ix_candidates_position_id", "candidates", ["position_id"], unique=False)
    op.create_table(
        "payroll_runs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("institution_id", sa.UUID(), nullable=False),
        sa.Column("period", sa.Date(), nullable=False),
        sa.Column("schedule_version_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.Enum("DRAFT", "APPROVED", name="payroll_run_status"), nullable=False),
        sa.Column("approved_by", sa.UUID(), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["schedule_version_id"], ["payroll_schedule_versions.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("institution_id", "period", name="uq_payroll_runs_period"),
    )
    op.create_index("ix_payroll_runs_institution_id", "payroll_runs", ["institution_id"], unique=False)
    op.create_table(
        "employees",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("institution_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("candidate_id", sa.UUID(), nullable=True),
        sa.Column("full_name", sa.String(length=200), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("department", sa.String(length=100), nullable=False),
        sa.Column("hire_date", sa.Date(), nullable=False),
        sa.Column("gross_monthly_salary_xaf", sa.BigInteger(), nullable=False),
        sa.Column("status", sa.Enum("ACTIVE", "TERMINATED", name="employee_status"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["candidate_id"], ["candidates.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_employees_institution_id", "employees", ["institution_id"], unique=False)
    op.create_index("ix_employees_user_id", "employees", ["user_id"], unique=False)
    op.create_table(
        "payslips",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("institution_id", sa.UUID(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("employee_id", sa.UUID(), nullable=False),
        sa.Column("period", sa.Date(), nullable=False),
        sa.Column("gross_xaf", sa.BigInteger(), nullable=False),
        sa.Column("cnps_employee_xaf", sa.BigInteger(), nullable=False),
        sa.Column("cnps_employer_xaf", sa.BigInteger(), nullable=False),
        sa.Column("taxable_base_xaf", sa.BigInteger(), nullable=False),
        sa.Column("irpp_xaf", sa.BigInteger(), nullable=False),
        sa.Column("net_xaf", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("gross_xaf >= 0", name="ck_payslips_gross_nonnegative"),
        sa.ForeignKeyConstraint(["run_id"], ["payroll_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("institution_id", "employee_id", "period", name="uq_payslips_employee_period"),
    )
    op.create_index("ix_payslips_employee_id", "payslips", ["employee_id"], unique=False)
    op.create_index("ix_payslips_institution_id", "payslips", ["institution_id"], unique=False)
    op.create_table(
        "attendance_shifts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("institution_id", sa.UUID(), nullable=False),
        sa.Column("employee_id", sa.UUID(), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("qr_token_jti", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["employee_id"], ["employees.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("qr_token_jti"),
    )
    op.create_index("ix_attendance_shifts_employee_id", "attendance_shifts", ["employee_id"], unique=False)
    op.create_index("ix_attendance_shifts_institution_id", "attendance_shifts", ["institution_id"], unique=False)
    op.create_table(
        "leave_requests",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("institution_id", sa.UUID(), nullable=False),
        sa.Column("employee_id", sa.UUID(), nullable=False),
        sa.Column("starts_on", sa.Date(), nullable=False),
        sa.Column("ends_on", sa.Date(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("status", sa.Enum("PENDING", "APPROVED", "REJECTED", name="leave_status"), nullable=False),
        sa.Column("decided_by", sa.UUID(), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["employee_id"], ["employees.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_leave_requests_employee_id", "leave_requests", ["employee_id"], unique=False)
    op.create_index("ix_leave_requests_institution_id", "leave_requests", ["institution_id"], unique=False)
    op.create_table(
        "performance_reviews",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("institution_id", sa.UUID(), nullable=False),
        sa.Column("employee_id", sa.UUID(), nullable=False),
        sa.Column("reviewer_id", sa.UUID(), nullable=False),
        sa.Column("period", sa.Date(), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column("comments", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("rating >= 1 AND rating <= 5", name="ck_performance_reviews_rating_range"),
        sa.ForeignKeyConstraint(["employee_id"], ["employees.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_performance_reviews_employee_id", "performance_reviews", ["employee_id"], unique=False)
    op.create_index("ix_performance_reviews_institution_id", "performance_reviews", ["institution_id"], unique=False)
    op.create_table(
        "attendance_records",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("institution_id", sa.UUID(), nullable=False),
        sa.Column("shift_id", sa.UUID(), nullable=False),
        sa.Column("employee_id", sa.UUID(), nullable=False),
        sa.Column("checked_in_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["shift_id"], ["attendance_shifts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("shift_id", "employee_id", name="uq_attendance_records_shift_employee"),
    )
    op.create_index("ix_attendance_records_institution_id", "attendance_records", ["institution_id"], unique=False)
    # ### end Alembic commands ###

    # Row-level tenant isolation, same FORCE + SET LOCAL pattern as every
    # other tenant-owned table in this repo.
    for table in (
        "assets",
        "notifications",
        "payroll_schedule_versions",
        "positions",
        "asset_movements",
        "candidates",
        "payroll_runs",
        "employees",
        "payslips",
        "attendance_shifts",
        "leave_requests",
        "performance_reviews",
        "attendance_records",
    ):
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"""
            CREATE POLICY tenant_isolation ON {table}
            USING (
                current_setting('app.is_platform_admin', true) = 'true'
                OR institution_id = NULLIF(current_setting('app.current_institution_id', true), '')::uuid
            )
            WITH CHECK (
                current_setting('app.is_platform_admin', true) = 'true'
                OR institution_id = NULLIF(current_setting('app.current_institution_id', true), '')::uuid
            )
            """
        )


def downgrade() -> None:
    for table in (
        "assets",
        "notifications",
        "payroll_schedule_versions",
        "positions",
        "asset_movements",
        "candidates",
        "payroll_runs",
        "employees",
        "payslips",
        "attendance_shifts",
        "leave_requests",
        "performance_reviews",
        "attendance_records",
    ):
        op.execute(f"DROP POLICY IF EXISTS tenant_isolation ON {table}")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_attendance_records_institution_id", table_name="attendance_records")
    op.drop_table("attendance_records")
    op.drop_index("ix_performance_reviews_institution_id", table_name="performance_reviews")
    op.drop_index("ix_performance_reviews_employee_id", table_name="performance_reviews")
    op.drop_table("performance_reviews")
    op.drop_index("ix_leave_requests_institution_id", table_name="leave_requests")
    op.drop_index("ix_leave_requests_employee_id", table_name="leave_requests")
    op.drop_table("leave_requests")
    op.drop_index("ix_attendance_shifts_institution_id", table_name="attendance_shifts")
    op.drop_index("ix_attendance_shifts_employee_id", table_name="attendance_shifts")
    op.drop_table("attendance_shifts")
    op.drop_index("ix_payslips_institution_id", table_name="payslips")
    op.drop_index("ix_payslips_employee_id", table_name="payslips")
    op.drop_table("payslips")
    op.drop_index("ix_employees_user_id", table_name="employees")
    op.drop_index("ix_employees_institution_id", table_name="employees")
    op.drop_table("employees")
    op.drop_index("ix_payroll_runs_institution_id", table_name="payroll_runs")
    op.drop_table("payroll_runs")
    op.drop_index("ix_candidates_position_id", table_name="candidates")
    op.drop_index("ix_candidates_institution_id", table_name="candidates")
    op.drop_table("candidates")
    op.drop_index("ix_asset_movements_institution_id", table_name="asset_movements")
    op.drop_index("ix_asset_movements_asset_id", table_name="asset_movements")
    op.drop_table("asset_movements")
    op.drop_index("ix_positions_institution_id", table_name="positions")
    op.drop_table("positions")
    op.drop_index("ix_payroll_schedule_versions_institution_id", table_name="payroll_schedule_versions")
    op.drop_table("payroll_schedule_versions")
    op.drop_index("ix_notifications_user_id", table_name="notifications")
    op.drop_index("ix_notifications_institution_id", table_name="notifications")
    op.drop_table("notifications")
    op.drop_index("ix_assets_institution_id", table_name="assets")
    op.drop_table("assets")
    # ### end Alembic commands ###
