"""academic phase 4 courses grades attendance exams

Revision ID: ff93b50d88c7
Revises: cf3d0d05d5b9
Create Date: 2026-09-11 13:06:47.853068
"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = 'ff93b50d88c7'
down_revision: str | None = 'cf3d0d05d5b9'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.Column('program_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('institution_id', 'program_id', 'code', name='uq_courses_program_code')
    )
    op.create_index('ix_courses_institution_id', 'courses', ['institution_id'], unique=False)
    op.create_index('ix_courses_program_id', 'courses', ['program_id'], unique=False)
    op.create_table('course_offerings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('term_id', sa.UUID(), nullable=False),
    sa.Column('instructor_id', sa.UUID(), nullable=False),
    sa.Column('room', sa.String(length=100), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['term_id'], ['terms.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'term_id', name='uq_course_offerings_course_term')
    )
    op.create_index('ix_course_offerings_institution_id', 'course_offerings', ['institution_id'], unique=False)
    op.create_index('ix_course_offerings_instructor_id', 'course_offerings', ['instructor_id'], unique=False)
    op.create_index('ix_course_offerings_term_id', 'course_offerings', ['term_id'], unique=False)
    op.create_table('course_prerequisites',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('prerequisite_course_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prerequisite_course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'prerequisite_course_id', name='uq_course_prerequisites_edge')
    )
    op.create_index('ix_course_prerequisites_institution_id', 'course_prerequisites', ['institution_id'], unique=False)
    op.create_table('assessments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.Column('course_offering_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('max_score', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_offering_id'], ['course_offerings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_assessments_course_offering_id', 'assessments', ['course_offering_id'], unique=False)
    op.create_index('ix_assessments_institution_id', 'assessments', ['institution_id'], unique=False)
    op.create_index(
        'ix_assessments_offering_created', 'assessments', ['course_offering_id', 'created_at'], unique=False
    )
    op.create_table('attendance_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.Column('course_offering_id', sa.UUID(), nullable=False),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_offering_id'], ['course_offerings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_offering_id', 'session_date', name='uq_attendance_sessions_offering_date')
    )
    op.create_index(
        'ix_attendance_sessions_course_offering_id', 'attendance_sessions', ['course_offering_id'], unique=False
    )
    op.create_index('ix_attendance_sessions_institution_id', 'attendance_sessions', ['institution_id'], unique=False)
    op.create_table('course_registrations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('enrollment_id', sa.UUID(), nullable=False),
    sa.Column('course_offering_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_offering_id'], ['course_offerings.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollments.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'course_offering_id', name='uq_course_registrations_student_offering')
    )
    op.create_index('ix_course_registrations_institution_id', 'course_registrations', ['institution_id'], unique=False)
    op.create_index('ix_course_registrations_student_id', 'course_registrations', ['student_id'], unique=False)
    op.create_table('exam_schedules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.Column('term_id', sa.UUID(), nullable=False),
    sa.Column('course_offering_id', sa.UUID(), nullable=False),
    sa.Column('room', sa.String(length=100), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_offering_id'], ['course_offerings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['term_id'], ['terms.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_offering_id', name='uq_exam_schedules_course_offering')
    )
    op.create_index('ix_exam_schedules_institution_id', 'exam_schedules', ['institution_id'], unique=False)
    op.create_index('ix_exam_schedules_room', 'exam_schedules', ['term_id', 'room'], unique=False)
    op.create_index('ix_exam_schedules_term_id', 'exam_schedules', ['term_id'], unique=False)
    op.create_table('attendance_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.Column('attendance_session_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('present', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['attendance_session_id'], ['attendance_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attendance_session_id', 'student_id', name='uq_attendance_records_session_student')
    )
    op.create_index('ix_attendance_records_institution_id', 'attendance_records', ['institution_id'], unique=False)
    op.create_index('ix_attendance_records_student_id', 'attendance_records', ['student_id'], unique=False)
    op.create_table('grades',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.Column('assessment_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assessment_id', 'student_id', name='uq_grades_assessment_student')
    )
    op.create_index('ix_grades_institution_id', 'grades', ['institution_id'], unique=False)
    op.create_index('ix_grades_student_id', 'grades', ['student_id'], unique=False)
    op.create_table('grade_appeals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.Column('grade_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column(
        'status',
        sa.Enum('SUBMITTED', 'UNDER_REVIEW', 'ACCEPTED', 'REJECTED', name='appeal_status'),
        nullable=False,
    ),
    sa.Column('reviewer_notes', sa.Text(), nullable=True),
    sa.Column('decided_by', sa.UUID(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['grade_id'], ['grades.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_grade_appeals_grade_id', 'grade_appeals', ['grade_id'], unique=False)
    op.create_index('ix_grade_appeals_institution_id', 'grade_appeals', ['institution_id'], unique=False)
    op.create_index('ix_grade_appeals_student_id', 'grade_appeals', ['student_id'], unique=False)
    op.create_table('grade_audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.Column('grade_id', sa.UUID(), nullable=False),
    sa.Column('changed_by', sa.UUID(), nullable=False),
    sa.Column('old_score', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('new_score', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['grade_id'], ['grades.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_grade_audit_logs_grade_id', 'grade_audit_logs', ['grade_id'], unique=False)
    op.create_index('ix_grade_audit_logs_institution_id', 'grade_audit_logs', ['institution_id'], unique=False)
    # ### end Alembic commands ###

    # Row-level tenant isolation, same FORCE + SET LOCAL pattern as every
    # other tenant-owned table in this service (see academic initial schema
    # migration for the full rationale).
    for table in (
        "courses",
        "course_offerings",
        "course_prerequisites",
        "assessments",
        "attendance_sessions",
        "course_registrations",
        "exam_schedules",
        "attendance_records",
        "grades",
        "grade_appeals",
        "grade_audit_logs",
    ):
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"""
            CREATE POLICY tenant_isolation ON {table}
            USING (
                current_setting('app.is_platform_admin', true) = 'true'
                OR institution_id = NULLIF(current_setting('app.current_institution_id', true), '')::uuid
            )
            WITH CHECK (
                current_setting('app.is_platform_admin', true) = 'true'
                OR institution_id = NULLIF(current_setting('app.current_institution_id', true), '')::uuid
            )
            """
        )


def downgrade() -> None:
    for table in (
        "courses",
        "course_offerings",
        "course_prerequisites",
        "assessments",
        "attendance_sessions",
        "course_registrations",
        "exam_schedules",
        "attendance_records",
        "grades",
        "grade_appeals",
        "grade_audit_logs",
    ):
        op.execute(f"DROP POLICY IF EXISTS tenant_isolation ON {table}")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_grade_audit_logs_institution_id', table_name='grade_audit_logs')
    op.drop_index('ix_grade_audit_logs_grade_id', table_name='grade_audit_logs')
    op.drop_table('grade_audit_logs')
    op.drop_index('ix_grade_appeals_student_id', table_name='grade_appeals')
    op.drop_index('ix_grade_appeals_institution_id', table_name='grade_appeals')
    op.drop_index('ix_grade_appeals_grade_id', table_name='grade_appeals')
    op.drop_table('grade_appeals')
    op.drop_index('ix_grades_student_id', table_name='grades')
    op.drop_index('ix_grades_institution_id', table_name='grades')
    op.drop_table('grades')
    op.drop_index('ix_attendance_records_student_id', table_name='attendance_records')
    op.drop_index('ix_attendance_records_institution_id', table_name='attendance_records')
    op.drop_table('attendance_records')
    op.drop_index('ix_exam_schedules_term_id', table_name='exam_schedules')
    op.drop_index('ix_exam_schedules_room', table_name='exam_schedules')
    op.drop_index('ix_exam_schedules_institution_id', table_name='exam_schedules')
    op.drop_table('exam_schedules')
    op.drop_index('ix_course_registrations_student_id', table_name='course_registrations')
    op.drop_index('ix_course_registrations_institution_id', table_name='course_registrations')
    op.drop_table('course_registrations')
    op.drop_index('ix_attendance_sessions_institution_id', table_name='attendance_sessions')
    op.drop_index('ix_attendance_sessions_course_offering_id', table_name='attendance_sessions')
    op.drop_table('attendance_sessions')
    op.drop_index('ix_assessments_offering_created', table_name='assessments')
    op.drop_index('ix_assessments_institution_id', table_name='assessments')
    op.drop_index('ix_assessments_course_offering_id', table_name='assessments')
    op.drop_table('assessments')
    op.drop_index('ix_course_prerequisites_institution_id', table_name='course_prerequisites')
    op.drop_table('course_prerequisites')
    op.drop_index('ix_course_offerings_term_id', table_name='course_offerings')
    op.drop_index('ix_course_offerings_instructor_id', table_name='course_offerings')
    op.drop_index('ix_course_offerings_institution_id', table_name='course_offerings')
    op.drop_table('course_offerings')
    op.drop_index('ix_courses_program_id', table_name='courses')
    op.drop_index('ix_courses_institution_id', table_name='courses')
    op.drop_table('courses')
    # ### end Alembic commands ###
